Discover network peers using DID service
nuts-foundation/nuts-node pull request #106
Opened 2021-03-02 09:22 UTC by reinkrul

2021-03-02 19:48 UTC, woutslakhorst requested changes
This PR feels very quick and dirty. It's part of a bigger design including:

- service specification in DIDs, what happens if the endpoint is incorrect for the given type. This is mainly part of a bolt, but in this case it's not.
- what if endpoints are removed?
- what if nodes are down (and will never come back)
- documentation
- helper APIs? Since manipulating endpoints is quite hard right now.

An epic issue can be used to track the entire progress.

2021-03-02 19:48 UTC, woutslakhorst commented on core/echo_mock.go
> +// MockEchoServer is a mock of EchoServer interface.
did you install the latest tools using the makefile? If so, what version is your mockgen on?

2021-03-02 19:48 UTC, woutslakhorst commented on docs/pages/did-administration-cookbook.rst
> +DID Document Administration Cookbook
this page won't be added to the index.

2021-03-02 19:48 UTC, woutslakhorst commented on network/interface.go
> +	AddPeer(address string) bool
Is there also a remove peer? eg: when an endpoint is removed...

2021-03-02 19:48 UTC, woutslakhorst commented on vdr/ambassador.go
> +		if service.Type == "nuts-network-grpc" {
constant

2021-03-02 19:48 UTC, woutslakhorst commented on vdr/ambassador.go
> +		if service.Type == "nuts-network-grpc" {
our docs should reflect this feature and enable admins to change the endpoint. If part of future development, it must be stated in an issue.

2021-03-02 19:48 UTC, woutslakhorst commented on vdr/types/common.go
> +func (d DocWriterDecorator) Write(document did.Document, metadata DocumentMetadata) error {
If the decorator fails, nothing is written. If the docWriter fails, connection will still be made....
The ordering and validity is very important and must be put in our specifications first.
If the decorator pattern is valid, depends on the specs.

2021-03-04 06:56 UTC, reinkrul commented
> This PR feels very quick and dirty. It's part of a bigger design including:
> 
> * service specification in DIDs, what happens if the endpoint is incorrect for the given type. This is mainly part of a bolt, but in this case it's not.
> * what if endpoints are removed?
> * what if nodes are down (and will never come back)
> * documentation
> * helper APIs? Since manipulating endpoints is quite hard right now.
> 
> An epic issue can be used to track the entire progress.

I tried to spec it in https://github.com/nuts-foundation/nuts-specification/pull/34

But: since this I remember discussing this I thought we could just squeeze it in but it has more facets to it than I anticipated. Since we don't really need peer discovery at this point because there aren't that many peers to begin with (which can be configured perfectly fine as bootstrap nodes).

I'll keep the spec PR so we can work on it, but I'll close this one for now (for later work).

2021-03-04 06:56 UTC, closed without merging