remove V1 network protocol and unused code
nuts-foundation/nuts-node pull request #1061
Opened 2022-05-04 13:26 UTC by woutslakhorst

closes #813

2022-05-05 07:00 UTC, gerardsn reviewed
Looks good to me, just some questions

2022-05-05 07:48 UTC, woutslakhorst commented on network/cmd/cmd.go
> -	flagSet.Int("network.v1.collectmissingpayloadsinterval", defs.ProtocolV1.CollectMissingPayloadsInterval, "Interval (in milliseconds) that specifies how often the node should check for missing payloa
not at the config level, it uses an incremental backoff. Jobs are stored in payload_jobs.db

2022-05-05 07:51 UTC, woutslakhorst commented on README.rst
> +jsonld.contexts.localmapping       [https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json=assets/contexts/lds-jws2020-v1.ldjson,https://schema.org=assets/contexts/schema-org-v13.ldjson,h
does not matter,  I think the order is random...

2022-05-05 07:52 UTC, gerardsn approved these changes

2022-05-05 08:02 UTC, woutslakhorst commented
@reinkrul comments? Since it's a lot of your code being removed. Maybe you have some pointers on dead-code?

2022-05-05 11:16 UTC, reinkrul commented
`network_integration_test` still mentions v1 and has specific v2 tests, is it still useful to have non-v2 tests and v2 tests since we only have v2 now?

2022-05-05 11:22 UTC, reinkrul requested changes

2022-05-05 11:22 UTC, reinkrul commented on README.rst
> +Go >= 1.17 is required.
`go.mod` states 1.18

2022-05-12 07:43 UTC, reinkrul approved these changes

2022-05-12 08:00 UTC, merged