Network: Send State when peer is behind and there are no new transactions
nuts-foundation/nuts-node pull request #1093
Opened 2022-05-11 09:28 UTC by gerardsn

reflects latest protocol update

If the Gossip does not result in the same XOR as its peer, the node now always makes an attempt at resolving their differences.

2022-05-12 08:03 UTC, reinkrul commented
Might be good to add an integration test for this? I suspect we could test this by starting one node which adds lots of TXs, then start a second node?

On the other hand, this really sounds like the "bootstrap/new node" scenario, which is probably already tested in the integration test?

2022-05-12 08:14 UTC, reinkrul requested changes

2022-05-12 08:14 UTC, reinkrul commented on network/transport/v2/handlers.go
> +	tempXor := xor.Xor(refs...)
Maybe some extra comments for understanding?
```suggestion
	// If our DAG is just missing the TXs from the gossip to get in sync with the peer's DAG, send TransactionListQuery.
	// Test this by XORing the TX refs from the gossip message with our DAG's XOR (should then equal peer DAG's XOR).
	tempXor := xor.Xor(refs...)
```

2022-05-12 09:39 UTC, gerardsn commented
> Might be good to add an integration test for this? I suspect we could test this by starting one node which adds lots of TXs, then start a second node?
> 
> On the other hand, this really sounds like the "bootstrap/new node" scenario, which is probably already tested in the integration test?

This specific change solves the case where a slow node is always behind and publishes a new transaction, but somehow the gossip didn't get through. In the old situation the peer would never be able to get its transaction out, but now it does. Added an integration test for this.

2022-05-13 09:12 UTC, reinkrul approved these changes

2022-05-13 09:47 UTC, merged