Reprocess command and API for rewalking the DAG
nuts-foundation/nuts-node pull request #1151
Opened 2022-05-24 12:57 UTC by woutslakhorst

Closes #1137 

Rebuilding the VCR and VDR uses Nats to publish events as a result of a dag.Walk. This is done to reduce the time a Read transaction is opened which may block Update transactions.
A call can be done done per contentType to reduce the number of events. Maximum number of events is currently limited to 1 million.

2022-05-31 10:02 UTC, gerardsn requested changes
Looks good. Just some minor things

2022-06-01 09:22 UTC, woutslakhorst commented on network/network.go
> +			end := start + +batchSize
indeed, but no worries +1 is the same as 1

2022-06-01 09:23 UTC, woutslakhorst commented on .circleci/config.yml
> +      - run: go test -p 1 -v $(go list ./... | circleci tests split) -race -coverprofile=cov/c_raw_$CIRCLE_NODE_INDEX.out
max number of parallel tests. The tests that use os.Env may not run in parallel. Luckily CircleCI uses 8 VMs to run tests in parallel. Each VM only has a single core so parallel tests from the go executable doesn't provide any performance improvements.

2022-06-01 09:26 UTC, woutslakhorst commented on network/network.go
> +				lastLC = tx.Clock()
it could, but it would require checking the length of the `txs` slice: `if len(txs) != 0; lastLC = txs[last].clock`. This is more code...

2022-06-01 09:27 UTC, woutslakhorst commented on network/network_test.go
> +		}, 100*time.Millisecond)
yes, but unfortunately testing if a parallel process didn't do something is quite hard.

2022-06-01 09:29 UTC, woutslakhorst commented on network/network_test.go
> +	t.Run("ok", func(t *testing.T) {
this is done by `test.WaitFor`. If it didn't finish in time with the `true` as return value, it'll fail

2022-06-01 09:29 UTC, woutslakhorst commented on network/network_test.go
> +		}, 100*time.Millisecond)
your point?

2022-06-01 09:30 UTC, woutslakhorst commented on network/network_test.go
> +	foundMutex := sync.Mutex{}
Both the main routine (test) and the subscriber routine are reading/writing the counter. If you run the tests with `-race` , they will occasionally fail with a race condition detected.

2022-06-01 09:32 UTC, woutslakhorst commented on network/network.go
> +func (n *Network) Reprocess(contentType string) {
It's a if-all-else-fails piece of functionality. Probably only used during development/test. We'll add more functionality if needed.

2022-06-01 12:28 UTC, gerardsn commented on network/network_test.go
> +	t.Run("ok", func(t *testing.T) {
aah.. this also explains my misinterpretation of the other tests

2022-06-01 14:05 UTC, merged