VCR: Validate that VCs only contain fields that are defined by JSON-LD context
nuts-foundation/nuts-node pull request #1190
Opened 2022-06-10 15:23 UTC by reinkrul

Fixes https://github.com/nuts-foundation/nuts-node/issues/1032

TODO:

- [x] Find out why proof is (almost) empty after compaction
- [x] Check whether we want VCs received through the network fail on these same rules (or should it only be a sanity check from our API). Answer: no; VCs should be stored, but only fields from context returned/indexed.

2022-06-23 11:31 UTC, woutslakhorst requested changes

2022-06-23 11:31 UTC, woutslakhorst commented on vcr/credential/validator.go
> +	options := ld.NewJsonLdOptions("") // TODO: why?
doesn't matter for your own comparison. The given string acts as "root" context name.

2022-10-03 10:03 UTC, reinkrul commented
Merge for v5, add to release notes that integrations can't pass legalBase.

2022-10-10 12:42 UTC, woutslakhorst requested changes

2022-10-10 12:42 UTC, woutslakhorst commented on docs/pages/release_notes.rst
> +Hazelnut (v5.0.0)
Coconut

2022-10-10 12:42 UTC, woutslakhorst commented on docs/pages/release_notes.rst
> +It has been added to the future v2 version of the credential, in which it can be used again.
Advice would be to remove the prop until V6. Then use V2 context.

2022-10-10 12:42 UTC, woutslakhorst commented on docs/pages/release_notes.rst
>  Chestnut update (v4.2.2)
No 4.2.3 and 4.2.4? Not backported, rebase master

2022-10-10 12:42 UTC, woutslakhorst commented on vcr/credential/validator_test.go
>  func TestNutsOrganizationCredentialValidator_Validate(t *testing.T) {
I would have expected that those new funcs to have their own tests. Keeps the test small.

2022-10-11 09:00 UTC, reinkrul commented
Feature becomes more complicated; compaction causes map with only an "ID" field to be "unmapped", so given:

```
{ credentialSubject: { id: "1234" } }
```

After compaction, becomes:

```
{ credentialSubject: "1234" }
```

2022-10-11 09:34 UTC, woutslakhorst commented
what about using expanded form instead of compacted form?

2022-10-11 18:40 UTC, reinkrul commented
> what about using expanded form instead of compacted form?

Can you describe how it would work? When we take VCs as input or marshal them, they're in compacted form. So the validation now works as follows:

```
inputJSON = toJSON(inputVC)
compactedJSON = compact(inputJSON) // removes fields not in JSON-LD context
normalize(inputJSON)
normalize(compactedJSON)
assert inputJSON == compactedJSON
```

2022-10-12 05:30 UTC, reinkrul commented
Assessed impact; VCs are validated when:

- Issuing VC
- Creating JWT grant token (thus, access tokens can't be requested for invalid NutsAuthCred)
- When verifying VCs, which is when:
  - Searching VCs (invalid NutsAuthCreds can't be found through search anymore)
  - Resolving VCs, used when introspecting access tokens (already issued access tokens can't be used any more)
- When verifying VPs, which is when:
  - VPs from the Auth module are validated, e.g. checking an IRMA signature in an access token

Since parties have only issued NutsAuthorizationCredentials for testing purposes, I don't think the actual usage of now considered invalid VCs will be a problem. That they don't appear in the search, however, might cause confusion. I'll add a warning in the log when the VC search encounters invalid VCs. Which can then be removed later again, in a subsequent version.

2022-10-13 11:04 UTC, merged