Redis support
nuts-foundation/nuts-node pull request #1250
Opened 2022-07-11 09:59 UTC by reinkrul

TODO:

- [x] Waiting for https://github.com/nuts-foundation/go-stoabs/pull/13
- [x] Documentation
- [x] End to end test: https://github.com/nuts-foundation/nuts-go-e2e-test/pull/27

2022-07-20 11:15 UTC, woutslakhorst requested changes

2022-07-20 11:15 UTC, woutslakhorst commented on docs/pages/deployment/server_options.rst
> +storage.bbolt.backup.directory
The config has changed, this must be added to the changelog

2022-07-20 11:18 UTC, woutslakhorst approved these changes
We need a heads-up after merging. Config has changed for master.

2022-07-20 11:41 UTC, reinkrul commented
> We need a heads-up after merging. Config has changed for master.

Wasn't entirely intentional, maybe we should revert it? On the other hand, I don't think BBolt backups were in v3 yet, so there's no reason we can't "break" it at this point since it wasn't in a release yet.

2022-07-20 14:46 UTC, reinkrul commented
Please review docs

2022-07-21 06:24 UTC, woutslakhorst requested changes

2022-07-21 06:24 UTC, woutslakhorst commented on docs/pages/deployment/database-configuration.rst
> +Make sure to include the directory in your backups and keep these on a safe place.
```suggestion
Make sure to include the directory in your backups and keep these in a safe place.
```

2022-07-21 06:24 UTC, woutslakhorst commented on docs/pages/deployment/database-configuration.rst
> +The token must have a vault policy which enables READ and WRITES rights on the path. In addition it needs to READ the token information "auth/token/lookup-self" which should be part of the default po
```suggestion
The token must have a vault policy which has READ and WRITES rights on the path. In addition it needs to READ the token information "auth/token/lookup-self" which should be part of the default policy.
```

2022-07-21 06:24 UTC, woutslakhorst commented on docs/pages/deployment/database-configuration.rst
> +Migrating from to Vault
```suggestion
Migrating to Vault
```

2022-07-21 06:24 UTC, woutslakhorst commented on docs/pages/deployment/database-configuration.rst
> +Migrating your private keys storage from the filesystem to Vault is relatively easy: just upload the keys to Vault under ``kv/nuts-private-keys``.
```suggestion
Migrating your private keys from the filesystem to Vault is relatively easy: just upload the keys to Vault under ``kv/nuts-private-keys``.
```

2022-07-21 06:24 UTC, woutslakhorst commented on docs/pages/deployment/database-configuration.rst
> +Alternatively you can use the ``fs2vault`` crypto command, which takes the directory containing the private keys as argument (it assumes the container is called `nuts-node`):
```suggestion
Alternatively you can use the ``fs2vault`` crypto command, which takes the directory containing the private keys as argument (the example assumes the container is called `nuts-node`):
```

2022-07-21 08:52 UTC, woutslakhorst approved these changes
I won't complain about the missing copyright ;)

2022-07-21 10:48 UTC, merged