Feature/1186 issuer backup store
nuts-foundation/nuts-node pull request #1251
Opened 2022-07-11 13:48 UTC by woutslakhorst

Closes #1186

Starting the issuer store will automatically resolve the state between backup and leia store.
Revocations are restored with the network.Reprocess command.

2022-07-13 05:02 UTC, reinkrul requested changes

2022-07-14 08:11 UTC, woutslakhorst commented on vcr/issuer/leia_store.go
> +	if err = newLeiaStore.handleRestore(issuedCollection, issuedBackupShelf, "id"); err != nil {
`handleRestore` is executed at startup. It detects the presence of the store and a missing index and will automatically rebuild the index.

2022-07-14 08:13 UTC, woutslakhorst commented on vcr/issuer/leia_store.go
> +	limit := 100
Probably the same as rebuilding the VDR/VCR from the DAG. But tests need to be done yes. (ballpark figure: >100/s

2022-07-14 08:14 UTC, woutslakhorst commented on vcr/issuer/leia_store.go
> +func NewLeiaIssuerStore(dbPath string, backupStore stoabs.KVStore) (Store, error) {
leia has a document store as well. It has an index and a store. This is an extra store to hook leia to a backup.

2022-07-14 08:41 UTC, reinkrul approved these changes

2022-07-14 09:04 UTC, merged