disable DAG.Verify at startup
nuts-foundation/nuts-node pull request #1259
Opened 2022-07-13 06:22 UTC by woutslakhorst

part of #1216 

Also removed `walk`, not used anymore.

2022-07-13 07:47 UTC, reinkrul reviewed
Remove in itself does look OK, but now we have dead code around. Is it useful to have as a CLI command? If we don't think so at this moment: it's so little code, i'd say just remove it (can be easily rewritten later).

2022-07-13 07:48 UTC, reinkrul requested changes
See comment

2022-07-14 07:59 UTC, woutslakhorst commented
> Remove in itself does look OK, but now we have dead code around. Is it useful to have as a CLI command? If we don't think so at this moment: it's so little code, i'd say just remove it (can be easily rewritten later).

As you can see, this is part of #1216 not the entire solution for that issue. Removing the verify has a higher priority as the command. The command still has to be added. TODOs have been added to the correct places in code.

2022-07-14 08:21 UTC, reinkrul approved these changes

2022-07-14 08:25 UTC, merged