VCR: Store VC after receiving from network
nuts-foundation/nuts-node pull request #136
Opened 2021-03-11 07:25 UTC by woutslakhorst

part of #66 
Closes #127

2021-03-11 14:10 UTC, reinkrul requested changes

2021-03-12 07:41 UTC, woutslakhorst commented on vcr/ambassador.go
> +func (n *ambassador) callback(tx dag.SubscriberTransaction, payload []byte) error {
nope, copy-paste of vdr. Removed it.

2021-03-12 07:43 UTC, woutslakhorst commented on vcr/ambassador.go
> +func (n *ambassador) callback(tx dag.SubscriberTransaction, payload []byte) error {
All verification of a VC is done through vcr.Verify because it requires access to both the VDR and Keystore

2021-03-12 07:44 UTC, woutslakhorst commented on vcr/interface.go
> +	// Write writes a VC to storage. Before writing, it calls Verify!
changed doc

2021-03-12 11:37 UTC, reinkrul approved these changes

2021-03-12 12:30 UTC, merged