Docs: tweak TLS offloading docs
nuts-foundation/nuts-node pull request #1414
Opened 2022-09-06 08:51 UTC by reinkrul

Closes https://github.com/nuts-foundation/nuts-node/issues/1363

2022-09-07 06:02 UTC, woutslakhorst requested changes

2022-09-07 06:02 UTC, woutslakhorst commented on docs/pages/deployment/recommended-deployment.rst
> +    There are features that will might the recommended deployment, e.g.:
```suggestion
    There are features that might change the recommended deployment, e.g.:
```

2022-09-14 14:29 UTC, reinkrul commented
Can you review this @woutslakhorst ?

2022-09-16 06:02 UTC, woutslakhorst approved these changes

2022-09-19 14:24 UTC, merged