doc: sort Redis keys with nested last (issue #1550)
nuts-foundation/nuts-node pull request #1583
Opened 2022-10-24 10:14 UTC by pascaldekloe

2022-10-24 11:07 UTC, reinkrul approved these changes
Before merge, run `make gen-docs` to regenerate docs (options table)

2022-10-26 11:15 UTC, woutslakhorst requested changes

2022-10-26 11:15 UTC, woutslakhorst commented on docs/generate_docs.go
> +// Len implements sort.Iterface.
Typos

2022-10-26 11:27 UTC, woutslakhorst approved these changes

2022-10-26 12:52 UTC, merged