Docs: clarify node bootstrap
nuts-foundation/nuts-node pull request #1604
Opened 2022-10-29 14:26 UTC by reinkrul

Closes #1595

2022-10-31 12:16 UTC, gerardsn requested changes
The issue suggest emphasizing step 3 to prevent the `root transaction already exists` issue.
IMO this fails to achieve that. Maybe also add a section or a note between `Configuring` and `Node Identity`?

2022-10-31 12:23 UTC, gerardsn commented
> Maybe also add a section or a note between `Configuring` and `Node Identity`?
Or perhaps update the node that is already there. (3-configure-your-node.rst#L95)

2022-11-01 15:01 UTC, gerardsn requested changes
Good improvement of the documentation. Some minor things left

2022-11-04 11:09 UTC, reinkrul commented on docs/pages/getting-started/3-configure-your-node.rst
> +    You'll have a private network with one single node. Perfect for local development, but a bit lonely.
yes

2022-11-04 17:44 UTC, gerardsn approved these changes
There are a lot of lists on this [page](https://nuts-node.readthedocs.io/en/docs-clarify-node-bootstrap/pages/getting-started/3-configure-your-node.html), but this a good update I'd say.

2022-11-04 17:44 UTC, gerardsn commented on docs/pages/getting-started/3-configure-your-node.rst
> +If you're using a YAML file to configure your node, the following snippet how to configure these properties:
```suggestion
If you're using a YAML file to configure your node, the following snippet shows how to configure these properties:
```

2022-11-06 06:09 UTC, merged