NATS: Acquire is too complicated
nuts-foundation/nuts-node pull request #1616
Opened 2022-11-03 10:56 UTC by reinkrul

Fixes https://github.com/nuts-foundation/nuts-node/issues/1615

2022-11-04 17:31 UTC, pascaldekloe requested changes

2022-11-04 17:31 UTC, pascaldekloe commented on docs/pages/deployment/server_options.rst
> +    events.nats.timeout                    30ns
Go, niet golang. Denk niet dat dit formaat iemand iets zegt. 😁 Beter de omschrijving van time.ParseDuration copieren hier.

2022-11-04 17:31 UTC, pascaldekloe commented on events/conn.go
> +		return nil, nil, fmt.Errorf("time-out/cancelled while acquiring NATS connection: %w", ctx.Err())
"NATS connection acquire: %w"

2022-11-04 17:31 UTC, pascaldekloe commented on events/conn.go
> +		if ctx.Err() != nil {
Check hardly applicable. Instead use a nats.Context in connectFunc instead.

2022-11-04 17:31 UTC, pascaldekloe commented on events/conn.go
> +		return data.(connectionAndContext).conn, data.(connectionAndContext).js, nil
We have generics now. No need for panic.

2022-11-08 13:44 UTC, reinkrul commented
Not really worth the effort

2022-11-08 13:44 UTC, closed without merging