update go-did to v0.4.0 and adjust usage accordingly
nuts-foundation/nuts-node pull request #1632
Opened 2022-11-09 13:23 UTC by woutslakhorst

fixes #1536

simple lib update and change in calling `doc.RemoveVerificationMethod`

2022-11-10 04:05 UTC, reinkrul requested changes

2022-11-10 04:05 UTC, reinkrul commented on vdr/doc/manipulator_test.go
> +		assert.NoError(t, err)
rename test, now indicates error flow

2022-11-10 12:33 UTC, reinkrul approved these changes

2022-11-14 08:28 UTC, woutslakhorst commented
No backport needed

2022-11-16 10:11 UTC, merged