Replace if-assert statements with require
nuts-foundation/nuts-node pull request #1637
Opened 2022-11-11 14:01 UTC by reinkrul

2022-11-14 15:32 UTC, gerardsn commented on auth/services/oauth/oauth_test.go
> +		require.ErrorContains(t, err, "JWT validity too long")
assert

2022-11-14 16:11 UTC, gerardsn requested changes
A couple of points
- [x] changing `.ldjson` context files is dangerous and should probably not be in this PR
- [ ] a couple of `require` statements too many
- [x] search for `if !assert` still finds a couple of more cases

2022-11-14 16:14 UTC, gerardsn commented on network/dag/verifier_test.go
>  		assert.Contains(t, err.Error(), "failed")
actually is part of this PR. Drop `require.Error` and make the other `assert.ErrorContains`

2022-11-15 08:29 UTC, reinkrul commented on core/echo_errors.go
> +	error
I needed it to be able to use ErrorContains in some other test

2022-11-15 08:39 UTC, gerardsn commented on core/echo_errors.go
> +	error
I missed the err in the implementation

2022-11-16 11:31 UTC, gerardsn reviewed
It looks like most `require.Error` statements only serve to prevent nil dereferencing in error validations using formats like `assert.Equal(t,"some error string", err.Error())`. Error validation in this format is just wrong, but it gets the job done. IMO we have (almost) no valid use-cases for `require.Error` or `require.ErrorContains`

2022-11-16 12:15 UTC, reinkrul commented
> It looks like most `require.Error` statements only serve to prevent nil dereferencing in error validations using formats like `assert.Equal(t,"some error string", err.Error())`. Error validation in this format is just wrong, but it gets the job done. IMO we have (almost) no valid use-cases for `require.Error` or `require.ErrorContains`

Because original scope was to eliminate the if-statements but hey, we came so far so let's go the last mile. I removed the unnecessary `Error()` statements when there's also an assert on its contents.

2022-11-17 05:52 UTC, merged