Increment client backoff when server returned unauthenticated
nuts-foundation/nuts-node pull request #1669
Opened 2022-11-18 13:25 UTC by woutslakhorst

fixes #1265 

store grpc error before closing connection, can then be used to increment backoff
currently backoff only increased for Code==16 (Unauthenticated)

2022-11-18 13:38 UTC, reinkrul requested changes

2022-11-18 13:38 UTC, reinkrul commented on network/transport/grpc/connection.go
> +	errStatus        *status.Status
you could use a `atomic.Pointer` (with generics), to avoid having to use the mutex;

```go
status atomic.Pointer[status.Status]
```

2022-11-18 13:38 UTC, reinkrul commented on network/transport/grpc/connection.go
> +	SetErrorStatus(status *status.Status)
I don't think the interface should allow access to this func. Replace it with `atomic.Pointer` and it can go anyways

2022-11-21 07:02 UTC, reinkrul requested changes

2022-11-21 07:02 UTC, reinkrul commented on network/transport/grpc/connection.go
> +	mc.mux.RLock()
you don't need the mutex now?

2022-11-21 10:30 UTC, woutslakhorst commented on network/transport/grpc/connection.go
> +	mc.mux.RLock()
true

2022-11-21 10:51 UTC, reinkrul approved these changes

2022-11-25 07:42 UTC, merged