VCR: Fix VC validator
nuts-foundation/nuts-node pull request #1677
Opened 2022-11-21 12:19 UTC by reinkrul

2022-11-24 12:36 UTC, stevenvegt requested changes
A new context should also be published on the nuts.nl website.
Also, for each context change, create a test credential with proof and make sure all previous versions are still compatible and still have a valid signature.

2022-11-25 13:59 UTC, reinkrul commented
The plot thickens:
- Current Nuts v1 context: canonicalized form includes the `localParameters` property, but not the child properties under it. Meaning the `localParameters` properties can be changed without invalidating the signature. Although JSON-LD playground includes them, but weird enough, not completely correctly.
- The suggested context change (adding `@vocab`) fixes this, but this invalidates current signatures (since now canonicalized form does contain the child properties).

Apparently, there is a `@json` type which does exactly what we want (https://www.w3.org/TR/json-ld11/#json-literals):
> At times, it is useful to include JSON within JSON-LD that is not interpreted as JSON-LD. Generally, a JSON-LD processor will ignore properties which don't map to [IRIs](https://tools.ietf.org/html/rfc3987#section-2), but this causes them to be excluded when performing various algorithmic transformations. But, when the data that is being described is, itself, JSON, it's important that it survives algorithmic transformations.

Tested this; canonicalized form does contain the JSON as-is (but normalized).

2022-11-25 15:00 UTC, stevenvegt requested changes
almost done!

2022-11-25 15:00 UTC, stevenvegt commented on vcr/signature/proof/jsonld.go
> +	println(string(canonicalDocument))
You missed a spot over here.

2022-12-01 09:47 UTC, reinkrul commented
> +update context on website

https://github.com/nuts-foundation/nuts-webpresence/pull/135

2022-12-01 10:11 UTC, stevenvegt approved these changes

2022-12-05 13:10 UTC, merged