Docs: production checklist
nuts-foundation/nuts-node pull request #1683
Opened 2022-11-22 06:23 UTC by reinkrul

Probably far from complete, please elaborate.

Fixes https://github.com/nuts-foundation/nuts-node/issues/1645

2022-11-25 08:00 UTC, woutslakhorst requested changes

2022-11-25 08:00 UTC, woutslakhorst commented on docs/pages/deployment/recommended-deployment.rst
> +  * Protect access to HTTP ``/internal``
and do not expose

2022-11-25 08:00 UTC, woutslakhorst commented on docs/pages/deployment/recommended-deployment.rst
> +  * Protect access to HTTP ``/internal``
+ only expose X, the rest not

2022-11-25 08:00 UTC, woutslakhorst commented on docs/pages/deployment/recommended-deployment.rst
> +  * Require client certificate on HTTP ``/n2n`` and gRPC endpoints.
ambiguous regarding reverse proxy

2022-11-30 10:57 UTC, stevenvegt commented on docs/pages/deployment/recommended-deployment.rst
> +  * Use a proxy in front of the node which terminates TLS
Say something about a proxy which prevents connection spamming?

2022-12-12 10:25 UTC, woutslakhorst approved these changes

2022-12-12 14:39 UTC, merged