Docs: improve OpenAPI examples to reflect actual data
nuts-foundation/nuts-node pull request #1697
Opened 2022-11-28 13:06 UTC by reinkrul

During past hackatons people keep getting confused about incorrect examples. Mostly about service ID which appears to be the service type in some examples, but which is actually the hash of the service.

This PR fixes examples containing DIDs (DIDs, verification method IDs and service IDs).

Partially fixes https://github.com/nuts-foundation/nuts-node/issues/1196

2022-11-30 07:52 UTC, stevenvegt requested changes
Change `example` to `examples` when you want to show multiple values.

2022-11-30 07:52 UTC, stevenvegt commented on docs/_static/didman/v1.yaml
> +          example:
If you want to show multiple examples, I think you need to use `examples:`

2022-11-30 07:52 UTC, stevenvegt commented on docs/_static/didman/v1.yaml
> +          example:
`examples`

2022-12-01 09:06 UTC, reinkrul commented
`examples` is not allowed, but I found a map of examples is the most idiomatic way (although not perfect since it is presented as the actual example).

2022-12-01 09:38 UTC, woutslakhorst approved these changes

2022-12-01 09:53 UTC, merged