Generate config options documentation based on engine flags
nuts-foundation/nuts-node pull request #17
Opened 2021-01-25 13:20 UTC by reinkrul

2021-01-28 09:13 UTC, stevenvegt requested changes
Nice! 👍 
Add this to our readme and makfile?

2021-01-29 07:53 UTC, woutslakhorst requested changes
Add to readme generation via makefile

2021-01-29 08:01 UTC, reinkrul commented
already present in makefile, documented usage in readme

2021-01-29 09:16 UTC, woutslakhorst approved these changes

2021-01-29 09:31 UTC, merged