Core: remove server response body HTTP client errors
nuts-foundation/nuts-node pull request #1719
Opened 2022-12-02 07:35 UTC by reinkrul

Since the server may return anything (e.g., binary response, or a very large blob), it's unsafe to include it in the error message: it gets logged and sometimes returned to the client.

Better to record it in the error struct, but not to include it in the error message.

Since it's still useful to print when a CLI command fails (due to non-OK server response), introduced a wrapper for all client commands.

2022-12-05 07:59 UTC, woutslakhorst reviewed
Just to check: response bodies are no longer logged server side when an error occurs? (Could be added to trace logging then?)

2022-12-12 15:20 UTC, reinkrul commented
Added debug logging for response body of remote Nuts Node's CreateAccessToken response.

Clients now just pass the response in the returned error, with a centralized error handling wrapper in root command registerer, that logs the body if the returned error is a RemoteServerError.

2022-12-14 08:30 UTC, woutslakhorst requested changes
Just the error name is misleading

2022-12-14 08:30 UTC, woutslakhorst commented on auth/api/v1/client.go
> +	"github.com/nuts-foundation/nuts-node/auth/log"
sorting

2022-12-14 08:30 UTC, woutslakhorst commented on core/http_client.go
> +type RemoteServerError struct {
I thought it was a custom error with specific contents. But it's actually a HttpError (>= 400)

2022-12-16 07:54 UTC, woutslakhorst approved these changes

2022-12-16 09:49 UTC, merged