Auth: CreateAccessToken must only return error details for validation errors
nuts-foundation/nuts-node pull request #1727
Opened 2022-12-02 12:32 UTC by reinkrul

This PR sanitizes errors created by `CreateAccessToken`, which is called by remote Nuts nodes. It should not return any internal error details, since they could point an attacker to possible vulnerabilities. Validation errors should be fine to return. 

This behavior is only applied in strict mode: in non-strict mode, it just returns the error details, as it did before (to aid debugging in non-production environments).

In order to achieve this, the following things changed:
- Always log the returned error as warning
- Move OAuth service interface to `oauth` package
- Rename `OAuthClient` to client
- removed validation checks from`buildAccessToken` that are already performed by `validateAccessTokenRequest`

Fixes https://github.com/nuts-foundation/nuts-node/issues/1527

2022-12-05 07:47 UTC, woutslakhorst requested changes
I don't see a test that checks if the description is empty when securemode is true

2022-12-13 07:25 UTC, reinkrul commented
Note: it will only fail with a generic error when signing fails, because it can't find a signing key or the signing itself fails.

2022-12-14 08:34 UTC, woutslakhorst requested changes

2022-12-16 07:53 UTC, woutslakhorst approved these changes

2022-12-16 09:18 UTC, merged