add some explanation on how IRMA path is constructed
nuts-foundation/nuts-node pull request #1745
Opened 2022-12-07 07:45 UTC by woutslakhorst

fixes #1646 

Describes some of the magic URL rewriting the Nuts node does for IRMA.

2022-12-07 09:46 UTC, gerardsn requested changes

2022-12-07 09:46 UTC, gerardsn commented on docs/pages/getting-started/5-irma-contract.rst
> +The IRMA ``session`` API will be mounted at that base path.
It's not clear to me if this API is part of Nuts or IRMA. 
Maybe add link to https://irma.app/docs/api-irma-server/ or point to IRMA in some other way.

2022-12-07 09:46 UTC, gerardsn commented on docs/pages/getting-started/5-irma-contract.rst
> +The IRMA ``session`` API will be mounted at that base path.
Or maybe this
```suggestion
IRMA's ``session`` API will be mounted at that base path.
```

2022-12-08 08:44 UTC, stevenvegt approved these changes

2022-12-08 14:31 UTC, merged