Allow for multiple organization credentials to exist
nuts-foundation/nuts-node pull request #1765
Opened 2022-12-12 14:05 UTC by woutslakhorst

Fixes #987

Name/City from signed login contract may now match any OrganizationCredential from requesting party. 

minor issue: non backport

2022-12-12 14:35 UTC, reinkrul requested changes
`notary.findVC` refers to the issue this fixes:

```go
	// Having multiple VCs with non-matching credentialSubjects for this care organization is not supported.
	// Will be supported when https://github.com/nuts-foundation/nuts-node/issues/987 is implemented.
	if len(result) > 1 {
		var credentialSubject interface{}
		for _, current := range result {
			if credentialSubject != nil && !reflect.DeepEqual(credentialSubject, current.CredentialSubject) {
				return "", "", errors.New("found multiple non-matching VCs, which is not supported")
			}
			credentialSubject = current.CredentialSubject
		}
	}
```

2022-12-12 14:35 UTC, reinkrul commented on auth/services/oauth/oauth.go
> +		log.Logger().Warn("Token request validation failed, requester does not have any credentials that match the organization name and city in the contract.")
```suggestion
		log.Logger().Warn("Token request validation failed, requester does not have any credential that match the organization name and city in the contract.")
```

2022-12-12 14:35 UTC, reinkrul commented on auth/services/oauth/oauth.go
> +			found = true
```suggestion
			found = true
			break
```

2022-12-15 22:36 UTC, gerardsn reviewed
`make install-tools && make gen-api`

2022-12-16 05:31 UTC, reinkrul approved these changes

2022-12-16 07:40 UTC, merged