Limit the path to 200 chars in prometheus metrics
nuts-foundation/nuts-node pull request #1770
Opened 2022-12-14 12:57 UTC by stevenvegt

Fixes NTS-009: #1716
Number of 200 is arbitrary, open for discussion.

2022-12-15 05:22 UTC, reinkrul commented
What is the longest, sane path length given the current API? That's the base limit, I think.

2022-12-15 23:10 UTC, gerardsn reviewed
I thought this issue was about something else. 
The metrics collect a lot of statistics on every url that is called. For example, calling
:1323/status
:1323/status/diagnostics
:1323/does/not/exist
on a new node returns the following metrics

<details>
  <summary>collapsed /metrics</summary>
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 4.3229e-05
go_gc_duration_seconds{quantile="0.25"} 8.9297e-05
go_gc_duration_seconds{quantile="0.5"} 0.000113527
go_gc_duration_seconds{quantile="0.75"} 0.00039114
go_gc_duration_seconds{quantile="1"} 0.001229421
go_gc_duration_seconds_sum 0.013015323
go_gc_duration_seconds_count 50
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 37
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.19.3"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 8.860488e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 1.43471952e+08
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.497244e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 779525
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 9.972784e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 8.860488e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 1.531904e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 1.314816e+07
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 55221
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 352256
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 1.4680064e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.671145048466145e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 834746
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 4800
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 15600
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 185232
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 195840
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 1.2280632e+07
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 751180
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 2.097152e+06
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 2.097152e+06
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 2.9209864e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 10
# HELP http_request_duration_seconds The HTTP request latencies in seconds.
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="0.005"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="0.01"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="0.025"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="0.05"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="0.1"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="0.25"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="0.5"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="1"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="2.5"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="5"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="10"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status",le="+Inf"} 12
http_request_duration_seconds_sum{code="200",method="GET",url="/status"} 0.000144282
http_request_duration_seconds_count{code="200",method="GET",url="/status"} 12
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="0.005"} 0
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="0.01"} 1
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="0.025"} 1
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="0.05"} 1
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="0.1"} 1
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="0.25"} 1
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="0.5"} 1
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="1"} 1
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="2.5"} 1
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="5"} 1
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="10"} 1
http_request_duration_seconds_bucket{code="200",method="GET",url="/status/diagnostics",le="+Inf"} 1
http_request_duration_seconds_sum{code="200",method="GET",url="/status/diagnostics"} 0.006171257
http_request_duration_seconds_count{code="200",method="GET",url="/status/diagnostics"} 1
http_request_duration_seconds_bucket{code="404",method="GET",url="/does/not/exist",le="0.005"} 1
http_request_duration_seconds_bucket{code="404",method="GET",url="/does/not/exist",le="0.01"} 1
http_request_duration_seconds_bucket{code="404",method="GET",url="/does/not/exist",le="0.025"} 1
http_request_duration_seconds_bucket{code="404",method="GET",url="/does/not/exist",le="0.05"} 1
http_request_duration_seconds_bucket{code="404",method="GET",url="/does/not/exist",le="0.1"} 1
http_request_duration_seconds_bucket{code="404",method [...]

2022-12-16 05:20 UTC, reinkrul commented
Yes, if you limit it to 200 chars you still have 200^70 (ish) possibilites to generate?

What I'm thinking:
- Check how Prometheus stores it internally -> an unbounded map is not okay (DoS attack possible). When it has a max. size, I'd say it's acceptable.
- Don't log calls to `public`, or shorten them to `/public`, or only the registered ones.

Another option is to only log the registered OpenAPI operations, but that sounds like a lot more work. Maybe we shouldn't enable the Echo/Prometheus logger at all?

2022-12-16 05:20 UTC, reinkrul reviewed
Yes, if you limit it to 200 chars you still have 200^70 (ish) possibilites to generate?

What I'm thinking:
- Check how Prometheus stores it internally -> an unbounded map is not okay (DoS attack possible). When it has a max. size, I'd say it's acceptable.
- Don't log calls to `public`, or shorten them to `/public`, or only the registered ones.

Another option is to only log the registered OpenAPI operations, but that sounds like a lot more work. Maybe we shouldn't enable the Echo/Prometheus logger at all?

2022-12-16 07:11 UTC, woutslakhorst commented
> Another option is to only log the registered OpenAPI operations, but that sounds like a lot more work. Maybe we shouldn't enable the Echo/Prometheus logger at all?

Maybe the best solution because:
- A: it could have been a buy-1-get-1-for-free when we first enabled this. We wanted to get the /metrics endpoint and got echo metrics for free.
- B: Do we actually want this? Most monitor this through the reverse proxy since the implementation there is way better.

2022-12-16 08:29 UTC, reinkrul commented
> It's indeed not about the length but the number of different paths.
> 
> > Another option is to only log the registered OpenAPI operations, but that sounds like a lot more work. Maybe we shouldn't enable the Echo/Prometheus logger at all?
> 
> Maybe the best solution because:
> 
> * A: it could have been a buy-1-get-1-for-free when we first enabled this. We wanted to get the /metrics endpoint and got echo metrics for free.
> * B: Do we actually want this? Most monitor this through the reverse proxy since the implementation there is way better.

I vote for B (just use the access log or/with tooling designed for it, e.g. datadog and friends)

2023-01-03 13:04 UTC, woutslakhorst approved these changes

2023-01-05 10:39 UTC, reinkrul requested changes
Remove from docs:

> promhttp_ contains metrics related to HTTP calls to the Nuts node’s /metrics endpoint

2023-01-06 08:02 UTC, reinkrul commented
You can also remove the `github.com/labstack/echo-contrib` dependency

2023-01-16 10:07 UTC, reinkrul requested changes
`promhttp_` is still being returned, `http_` isn't

2023-01-16 10:07 UTC, reinkrul commented on docs/pages/deployment/monitoring.rst
>  * ``http_`` contains metrics related to HTTP calls to the Nuts node
```suggestion
* ``promhttp_`` contains metrics related to HTTP calls to the Nuts node's ``/metrics`` endpoint
```

2023-01-16 10:33 UTC, reinkrul approved these changes

2023-01-16 11:15 UTC, merged