Crypto: Add KID check wrapper for crypto storage backends
nuts-foundation/nuts-node pull request #1772
Opened 2022-12-14 14:31 UTC by stevenvegt

Fixes: NTS-007 #1723

Adds a wrapper for storage engines. For each function that accepts a kid param, the param gets validated for a provided kidPattern. This allows for multiple kid patterns in the future.

2022-12-15 09:59 UTC, reinkrul requested changes

2022-12-15 09:59 UTC, reinkrul commented on crypto/storage/wrapper_test.go
> +
```suggestion
```

2022-12-15 09:59 UTC, reinkrul commented on crypto/storage/wrapper_test.go
> +
```suggestion
```

2022-12-15 09:59 UTC, reinkrul commented on crypto/storage/wrapper_test.go
> +
```suggestion
```

2022-12-15 09:59 UTC, reinkrul commented on crypto/storage/wrapper_test.go
> +	"../server-certificate",
```suggestion
	"/etc/passwd",
	"../server-certificate",
```

2022-12-15 10:00 UTC, reinkrul commented
I agree we can ignore the error. Unless there's linter instruction or similar we can apply in code.

2022-12-16 07:56 UTC, woutslakhorst commented on crypto/storage/wrapper.go
> +package storage
copyright

2022-12-16 09:51 UTC, reinkrul approved these changes

2022-12-16 10:16 UTC, merged