Allow CORS to be enabled on specific HTTP interfaces
nuts-foundation/nuts-node pull request #178
Opened 2021-03-23 07:55 UTC by reinkrul

Required for development (and some deployment setups) on `auth` for IRMA flow

Fixes #60

2021-03-24 07:40 UTC, stevenvegt approved these changes

2021-03-25 07:11 UTC, woutslakhorst requested changes
`cors: true` translates to `allow-origin: *` since that is the standard config for echo. That is a bit too much, you should be able to define the domains.

2021-03-25 07:59 UTC, reinkrul commented
> `cors: true` translates to `allow-origin: *` since that is the standard config for echo. That is a bit too much, you should be able to define the domains.

I thought about this too, since you have more options than just `AllowOrigin` (`allowed http methods` for instance). But I guess the `origin` parameter is so important that we should add it. I'd say for now, if you'd really like to specify the `http methods` parameter in your deployment scenario you'll just have to put a proxy in front of it.

Furthermore, we should disallow `origin = *` in strictmode.

2021-03-26 06:59 UTC, woutslakhorst approved these changes

2021-03-26 10:46 UTC, merged