Add the crypto storage abstraction spec
nuts-foundation/nuts-node pull request #1828
Opened 2023-01-11 10:04 UTC by stevenvegt

This PR adds the Crypto Storage Abstraction API Specification.

Fixes #1820 And is part of the #1810 project.

For easy review, I would advise to import the raw file into this online editor:
https://editor-next.swagger.io/

2023-01-13 10:00 UTC, reinkrul requested changes

2023-01-16 10:15 UTC, stevenvegt commented on docs/_static/crypto/nuts-storage-api-v1.yaml
> +    The endpoints mounted at /secret act as a key-value store which accepts keys as path.
What do you mean?

2023-01-16 10:19 UTC, stevenvegt commented on docs/_static/crypto/nuts-storage-api-v1.yaml
> +  /secrets:
Ah, no they do not. It's just `/secrets`. I think you misunderstand the line in the description:
>     The endpoints mounted at /secret act as a key-value store which accepts keys as path.
So, I'm going to fix that :)

2023-01-16 10:42 UTC, stevenvegt commented on docs/_static/crypto/nuts-storage-api-v1.yaml
> +    The endpoints mounted at /secret act as a key-value store which accepts keys as path.
Fixed, I removed that line.

2023-01-16 10:43 UTC, stevenvegt commented on docs/_static/crypto/nuts-storage-api-v1.yaml
> +        description: "Key under which the value should be stored. Note: The storage engine might encode these keys."
I added more information, better like this?

2023-01-16 10:45 UTC, stevenvegt commented on docs/_static/crypto/nuts-storage-api-v1.yaml
> +openapi: "3.0.0"
Currently this is a contract between the Nuts-node and an implementations, not much different from the current API specifications in sibling folders. I agree that the path is very obscure. A separate repository for all our api specifications would probably be more elegant, or event a less obscure path that the "docs" directory.

2023-01-16 12:00 UTC, reinkrul commented on docs/_static/crypto/nuts-storage-api-v1.yaml
> +        description: "Key under which the value should be stored. Note: The storage engine might encode these keys."
Not really, it still doesn't tell you what is allowed. If everything is allowed, fine too, just asking. If there are any restrictions, we should mention them (and if not, then it's OK).

2023-01-19 09:05 UTC, reinkrul approved these changes

2023-01-23 09:35 UTC, merged