Network: connection manager cleanup
nuts-foundation/nuts-node pull request #1840
Opened 2023-01-19 11:13 UTC by gerardsn

This should contain no functional changes
removes unused struct values / interfaces / tests
small refactor in start/stop to improve readability

2023-01-19 11:18 UTC, gerardsn commented on network/transport/grpc/connection_manager.go
> -		}(prot)
does wrapping this in a function have any side effects?

2023-01-20 14:59 UTC, woutslakhorst requested changes
With removing the `Stop()` there's no longer an option to stop the grpcServer gracefully. The connectionManager creates a background context and has to stop it on its own.

2023-01-20 16:06 UTC, gerardsn commented
Not sure what you mean. `Stop()` is not removed, biggest change there is that it no longer sets everything to nil after closing.

2023-01-23 07:53 UTC, woutslakhorst commented
> Not sure what you mean. `Stop()` is not removed, biggest change there is that it no longer sets everything to nil after closing.

Hmmm don't know what I was smoking...

2023-01-23 07:53 UTC, woutslakhorst approved these changes

2023-01-23 09:43 UTC, merged