Network: fix goroutine leak on shutdown in v2 protocol
nuts-foundation/nuts-node pull request #1901
Opened 2023-02-17 14:44 UTC by reinkrul

Part of https://github.com/nuts-foundation/nuts-node/issues/1900

2023-02-20 07:54 UTC, woutslakhorst requested changes
👍 on using contexts to stop procedures

2023-02-20 07:54 UTC, woutslakhorst commented on network/transport/v2/protocol.go
> +	ctx := p.ctx // use copy of pointer to avoid data race
copy of pointer still points to same instance.

2023-02-20 07:54 UTC, woutslakhorst commented on network/transport/v2/protocol.go
> +	p.listHandler = newTransactionListHandler(p.ctx, func(peer transport.Peer, envelope *Envelope) error {
change the `handleFunc` signature so the ctx is passed as well and you don't need a copy. HandleTransactionList should reuse the context passed by the TransctionListHandler, not the context from the protocol.

2023-02-20 15:29 UTC, gerardsn commented on network/transport/v2/peer_diagnostics_test.go
>  		wg.Done()
unrelate to this PR, but this test is broken. it doesn't wait...

2023-02-22 09:11 UTC, woutslakhorst approved these changes

2023-02-22 11:11 UTC, merged