Auth: only connect to HTTPS endpoints when in strict mode
nuts-foundation/nuts-node pull request #1922
Opened 2023-02-24 10:11 UTC by reinkrul

2023-03-03 08:48 UTC, gerardsn reviewed
how does this work with TLS offloading in proxy?

2023-03-03 08:48 UTC, gerardsn commented on docs/pages/deployment/configuration.rst
> +Interacting with remote Nuts nodes requires HTTPS: it will refuse to connect to plain HTTP endpoints when in strict mode.
this is very vague. "internal" endpoints (/internal, /health, /status, ...) do not require https

2023-03-03 08:49 UTC, gerardsn commented on docs/pages/deployment/configuration.rst
> +Interacting with remote Nuts nodes requires HTTPS: it will refuse to connect to plain HTTP endpoints when in strict mode.
aah, missed the `remote` part

2023-03-04 13:37 UTC, reinkrul commented
> how does this work with TLS offloading in proxy?

I'd about accessing remote endpoints, regardless of how the remote node handles TLS offloading you'll be connecting to an HTTPS endpoint. We don't support outgoing proxies.

2023-03-06 13:43 UTC, woutslakhorst requested changes
Using the engine level interface on the Wrapper is not a good idea. This creates spaghetti. I think it would be cleaner to move client logic from the API layer to the services layer where the configuration has been loaded properly.

2023-03-07 06:01 UTC, reinkrul commented
I agree, will be a larger refactor though.

2023-03-10 15:22 UTC, woutslakhorst commented on auth/api/v1/api.go
>  	"fmt"
sort imports, the imports on this file are a mess

2023-03-10 15:33 UTC, woutslakhorst requested changes

2023-03-10 15:33 UTC, woutslakhorst commented on auth/api/v1/api.go
> +	strictMode         bool
unused

2023-03-10 15:33 UTC, woutslakhorst commented on auth/api/v1/api.go
> +func (w *Wrapper) Configure(config core.ServerConfig) error {
Can be removed now?

2023-03-10 15:33 UTC, woutslakhorst commented on core/engine.go
> +	for _, router := range system.Routers {
May be removed now?

2023-03-13 14:37 UTC, reinkrul commented on core/engine.go
> +	for _, router := range system.Routers {
Forgot to revert, good one

2023-03-20 10:15 UTC, stevenvegt commented on auth/services/oauth/relying_party.go
> +	if err != nil {
better to check the scheme after the parsing?

2023-03-20 10:16 UTC, stevenvegt requested changes
Move the scheme check after the url parsing, so you don't have to perform these string operations

2023-03-20 14:47 UTC, woutslakhorst commented on auth/api/v1/client/types.go
> + * Copyright (C) 2021 Nuts community
Yes, we won 2 years

2023-03-20 14:48 UTC, woutslakhorst approved these changes

2023-03-20 15:03 UTC, merged