expand releasing with RCs
nuts-foundation/nuts-node pull request #1965
Opened 2023-03-08 14:53 UTC by woutslakhorst

Docs on creating RCs

2023-03-09 10:08 UTC, reinkrul approved these changes

2023-03-09 15:33 UTC, gerardsn requested changes
all 3 notations of rc format look different to me

2023-03-10 07:41 UTC, reinkrul commented
> all 3 notations of rc format look different to me

Maybe add a specific example just to make things simpler.

2023-03-10 15:17 UTC, woutslakhorst commented
> all 3 notations of rc format look different to me

There was indeed one error.

2023-03-13 08:29 UTC, gerardsn approved these changes

2023-03-15 07:36 UTC, merged