Docs: add proxy_buffering and client_max_body_size to example NGINX config
nuts-foundation/nuts-node pull request #2236
Opened 2023-06-09 13:37 UTC by reinkrul

Otherwise, bootstrapping nodes are disconnected (gRPC will report `RST_STREAM` error) due to (too) large pages being transmitted.

2023-06-09 13:53 UTC, gerardsn reviewed
The note below this example should then be removed?

I imagine we are als hitting this limit on bootstrap nodes: https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive_requests

2023-06-12 12:39 UTC, woutslakhorst commented
It would be indeed interesting to test these limits

2023-06-13 12:56 UTC, gerardsn commented
Either gRPC or the connection manager will reconnect. 

I think every message sent is a request, so each chunk in a range request (transactionList msg) probably counts as an individual request.

However, even if the nodes are in sync, the gossip and diagnostics broadcasts produce 720 requests/hour each with the default settings. This should result in a reconnect every ±42min?

2023-06-15 07:42 UTC, woutslakhorst requested changes
The note below says the same

2023-06-20 12:23 UTC, woutslakhorst approved these changes

2023-06-20 12:24 UTC, merged