Added last error and next connection attempt to addressbook stats
nuts-foundation/nuts-node pull request #2237
Opened 2023-06-12 14:05 UTC by woutslakhorst

closes #1929 

It'll now show the next connection attempt and the last error.
The next connection attempt is: previous + backoffValue

2023-06-13 08:23 UTC, reinkrul requested changes

2023-06-14 10:57 UTC, woutslakhorst commented on network/transport/grpc/addressbook.go
> +	error       atomic.Value
never use pointers unless needed?

2023-06-14 12:42 UTC, reinkrul commented on network/transport/grpc/addressbook.go
> +	error       atomic.Value
It's a generic `atomic.Value`?

2023-06-15 07:45 UTC, woutslakhorst commented on network/transport/grpc/addressbook.go
> +	error       atomic.Value
Indeed, value uses pointers as well....

2023-06-15 07:51 UTC, reinkrul approved these changes

2023-06-16 13:17 UTC, merged