Resolving did:key DIDs
nuts-foundation/nuts-node pull request #2523
Opened 2023-10-02 06:52 UTC by reinkrul

2023-10-05 06:41 UTC, woutslakhorst commented
Given the number of LOC, it wouldn't hurt to add the method

2023-10-09 06:25 UTC, reinkrul commented
I struggle decoding the public keys, so I'm first going ask at Sphereon about the `did:key` DID; it might only be used for the demo credential (and I suspect they'll remove it in future iterations).

2023-10-12 06:59 UTC, woutslakhorst requested changes

2023-10-12 06:59 UTC, woutslakhorst commented on vdr/didkey/resolver.go
> +package didkey
copyright

2023-10-12 06:59 UTC, woutslakhorst commented on vdr/didkey/resolver_test.go
> +	testCases := []testCase{
missing testcases for other key types

2023-10-13 09:57 UTC, reinkrul commented
Added lots of tests

2023-10-17 07:07 UTC, woutslakhorst approved these changes

2023-10-17 07:39 UTC, merged