Add submission requirement feature to presentation definition matching
nuts-foundation/nuts-node pull request #2559
Opened 2023-10-25 09:18 UTC by woutslakhorst

Closes #2540 

It looks like there's some duplicate code, but abstracting it with types and interfaces does more harm than good.
This functionality could then process the result of a `merge(...presentationDefinition)` function

2023-10-25 10:57 UTC, woutslakhorst commented
I forgot creating the `PresentationSubmission` when from_nested is used.

2023-10-30 13:47 UTC, woutslakhorst commented on vcr/pe/submission_requirement.go
> +	switch submissionRequirement.Rule {
Well, easily. I deduplicated using generics, it now has 5 lines of code less... Is it easier to read?

2023-10-30 14:37 UTC, gerardsn requested changes
Reviewed before today's changes
Some minor things

2023-10-31 08:23 UTC, woutslakhorst commented on vcr/pe/submission_requirement.go
> +			}
True, but that would be a concern for advanced submission processing?

2023-10-31 13:04 UTC, gerardsn approved these changes

2023-10-31 15:43 UTC, merged