Add Delete function to vcr wallet
nuts-foundation/nuts-node pull request #2759
Opened 2024-01-31 12:05 UTC by rolandgroen

A new Delete function is added to the wallet in the vcr/holder/wallet.go file. This function allows a credential to be removed from the wallet. Additionally, an interface in the vcr/holder/interface.go file has been updated to include this Delete function. Proper error handling and stats consistency are ensured in this implementation.

2024-01-31 12:18 UTC, reinkrul requested changes
Who needs this function? Is it correct that the REST API does not support this operation?

2024-01-31 12:18 UTC, reinkrul commented on vcr/holder/wallet.go
> +		return stats.Put(credentialCountStatsKey, binary.BigEndian.AppendUint32([]byte{}, currentCount+1))
I think this should be -1?

2024-01-31 12:18 UTC, reinkrul commented on vcr/holder/wallet.go
> +func (h wallet) Delete(ctx context.Context, subjectDID did.DID, id ssi.URI) error {
missing test

2024-02-20 09:48 UTC, rolandgroen commented
I'm not sure, how do we delete VCs from the wallet? Am I missing something?

2024-02-22 08:27 UTC, reinkrul commented
I've recently changed the implementation of the wallet from BBolt to SQL, so I'll reimplement this feature one of these days.

https://github.com/nuts-foundation/nuts-node/issues/2820

2024-02-22 08:27 UTC, closed without merging