Statuslist: Merge issuer and verifier
nuts-foundation/nuts-node pull request #2851
Opened 2024-03-01 15:51 UTC by gerardsn

closes #2850 

This PR
- merges all issuer and verifier logic in 1 object
- rewrite verifiers
- adds storage to the verifier
- moves issuing of StatusList2021Credential from the issuer to the joint package
- new db table

Files will be renamed after merging this PR to simplify reviewing, since Github saw the name changes as deleting/adding files.
store.go -> issuer.go
credential_status.go -> verifier.go

2024-03-04 14:54 UTC, woutslakhorst requested changes
credential != credential in comments. Propose to use StatusList2021Credential where applicable.

 some minor things to fix in godoc.

Optionally: I find it a bit hard to read, what do you think about:
- naming the tables: `status_list`, `status_list_credential` and `status_list_entry` (or _revocation)?
- name the package `revocation` and the service struct `StatusList2021`?

2024-03-04 14:54 UTC, woutslakhorst commented on vcr/statuslist2021/types.go
>  type CredentialSubject struct {
godoc

2024-03-04 14:54 UTC, woutslakhorst commented on vcr/statuslist2021/types.go
> +type CredentialStatus struct {
godoc

2024-03-05 18:14 UTC, gerardsn commented
I've added comments, and replaced credential with StatusList2021Credential where applicable.

Tables are renamed as proposed. (I think, status_list_credential and status_list are hard to keep apart)

I like revocation.StatusList2021 more than statuslist2021.CredentialStatus, but renaming the package also requires prefixing many of the exposed variables with StatusList2021. see https://github.com/nuts-foundation/nuts-node/pull/2851/commits/ca7a80ba57fd2ec1a76125b80106ebeef4103d8a. I'm not sure renaming the package is an improvement overall, but it would allow adding BitstringStatusList here. What do you think? (A better name for `CredentialStatus` would be good.) 

Yay or nay or removing the interfaces? They are not used...

2024-03-06 09:42 UTC, reinkrul commented on storage/sql_migrations/006_statuslist.sql
> +    -- the credential served at this URL may change over time, so we only keep the latest
incorrect docs

2024-03-06 13:52 UTC, woutslakhorst approved these changes

2024-03-06 14:21 UTC, merged