storage.sql.connection string redaction
nuts-foundation/nuts-node pull request #2972
Opened 2024-03-22 11:39 UTC by gerardsn

closes #2971 

I figured we might want to provide some useful info in the error, so this PR tries to redact the secret:

``` yaml
storage:
  sql:
    connection: "fake://user:password@example.com:123/db"
```

fails with

```
"unable to configure Storage: failed to initialize SQL database: unsupported SQL database connection: fake://<redacted>@example.com:123/db"
```

This might still fail, so just not logging the string ever is the safest option.

What do you think? If this is preferred I will add tests etc.

2024-03-22 12:25 UTC, reinkrul requested changes

2024-03-22 12:25 UTC, reinkrul commented on storage/config.go
> +	// This string may contain secrets (user:password), so should never be logged. User RedactedConnectionString.
User RedactedConnectionString?

2024-03-22 12:25 UTC, reinkrul commented on storage/config.go
> +func RedactedConnectionString(connection string) string {
can be unexported/private

2024-03-22 12:25 UTC, reinkrul commented on storage/config.go
> +	result := "<redacted>@" + url
probably good enough

2024-03-22 16:27 UTC, gerardsn commented on storage/config.go
> +	// This string may contain secrets (user:password), so should never be logged. User RedactedConnectionString.
removed now that is unexported

2024-03-22 16:43 UTC, gerardsn commented
changed to never log the connection string. Certain typos can cause the redaction to fail, its safer to just never log the connection string

2024-03-23 05:53 UTC, reinkrul approved these changes

2024-03-23 06:36 UTC, merged