Add sqlserver support to storage engine
nuts-foundation/nuts-node pull request #3057
Opened 2024-04-17 09:06 UTC by rolandgroen

This commit introduces support for the SQL Server database in the storage engine. A sqlserver driver has been added and appropriate configuration has been set up. This will allow users to use Microsoft SQL Server as one of the database options.

2024-04-17 09:08 UTC, rolandgroen commented
Assigning PR to @JorisHeadease to do some testing, if positive, pls add someone from nuts to review.

2024-04-17 09:40 UTC, reinkrul commented
Might be worth adding an end-to-end test, we already do this for Postgres and MySql, see `e2e-tests/oauth-flow/rfc021`.

Should be "just" a matter of creating a Docker Compose setup for MS SQL Server and adding it to the scripts.

2024-04-17 09:42 UTC, reinkrul requested changes
Also add documentation on it, see https://nuts-node.readthedocs.io/en/latest/pages/deployment/storage.html

(`storage.rst`)

2024-04-17 11:03 UTC, woutslakhorst commented
> This commit introduces support for the SQL Server database in the storage engine. A sqlserver driver has been added and appropriate configuration has been set up. This will allow users to use Microsoft SQL Server as one of the database options.

IS there a specific reason to add it, since Azure allows for MySQL and Postgres hosting options out of the box?

2024-05-07 06:49 UTC, reinkrul commented
Now supported; see https://github.com/nuts-foundation/nuts-node/pull/3080

2024-05-07 06:49 UTC, closed without merging