Storage: support Redis session storage
nuts-foundation/nuts-node pull request #3071
Opened 2024-04-23 16:34 UTC by rolandgroen

Rework of the https://github.com/nuts-foundation/nuts-node/pull/3065 PR, now for storing the session in Redis.

 - Added a new Session Type: RedisSessionStoreType 
 - Added configuration logic for Redis and RedisSessionStoreType
 - Implemented SessionDatabase and SessionStore for Redis

Remark / Notes

- Needed to patch go-stoabs to support TTL functions of redis

2024-04-23 18:16 UTC, reinkrul commented
What were the considerations to use `go-stoabs`?

Note that you don't need to use `go-stoabs` per se, since it was meant as abstraction for key-value stores for the Nuts node. It's only used in v5 features (and we might want to scrap it when doing away with did:nuts/gRPC network). By using it, you (might) lose Redis-specific features that could be useful (e.g. specific data types).

I'm not completely against using it if it brings advantages, but if it's just as easy to directly use the Redis driver, it could be preferred.

@woutslakhorst ?

2024-04-23 18:22 UTC, reinkrul requested changes

2024-04-24 09:38 UTC, woutslakhorst commented
> What were the considerations to use `go-stoabs`?
> 
> Note that you don't need to use `go-stoabs` per se, since it was meant as abstraction for key-value stores for the Nuts node. It's only used in v5 features (and we might want to scrap it when doing away with did:nuts/gRPC network). By using it, you (might) lose Redis-specific features that could be useful (e.g. specific data types).
> 
> I'm not completely against using it if it brings advantages, but if it's just as easy to directly use the Redis driver, it could be preferred.
> 
> Also important to note that, to enable session storage in Redis, you need to configure Redis storage (doh), which causes did:nuts/gRPC network data to be stored in Redis instead of on disk.
> 
> @woutslakhorst ?

I would prefer to have a redis session storage directly use the redis library. This enables you to use the key/value options with automatic expiry. Furthermore go-stoabs was designed for persistent storage.

2024-04-24 10:45 UTC, rolandgroen commented
I didn't know the rationale behind go-stoas, so I just aligned to the "way of working" with Redis.

I agree about the config split, you might even want to configure another Redis for sessions than for the network. The config will get a little more complex, and the session.type can be come implicit:

```
storage:
  redis:
    address: 127.0.0.1:6379
  sql:
    connection: postgres://..:..@127.0.0.1:5432/db
  session:
    redis:
      address: 127.0.0.1:6379
```

2024-04-24 10:56 UTC, rolandgroen commented
Refactored the code to directly use the redis library.

2024-04-25 04:57 UTC, reinkrul reviewed
I'm OK with the general approach (one last thing remaining). There's some duplicity in `storage.redis` and `session.redis` configuration now, but when v5 features are removed, `storage.redis` will be removed as well.

2024-04-25 04:57 UTC, reinkrul commented on go.mod
> +	github.com/nuts-foundation/go-stoabs v1.9.1-0.20240423163219-4ceec5cef809
I think we can revert this now?

2024-04-25 07:26 UTC, rolandgroen commented on go.mod
> +	github.com/nuts-foundation/go-stoabs v1.9.1-0.20240423163219-4ceec5cef809
Yes, rolled back

2024-04-25 08:28 UTC, reinkrul commented
I took the liberty of fixing some things I found (some simplifications, and use support for expiry from Miniredis). I hope you don't mind.

2024-04-25 08:29 UTC, reinkrul approved these changes

2024-04-25 08:40 UTC, merged