Check authz request URI and non-URI params
nuts-foundation/nuts-node pull request #3084
Opened 2024-05-03 14:42 UTC by gerardsn

2024-05-05 04:49 UTC, reinkrul requested changes

2024-05-05 04:49 UTC, reinkrul commented on auth/api/iam/openid4vp.go
> +			return r.sendAndHandleDirectPostError(ctx, oauth.OAuth2Error{Code: oauth.InvalidRequest, Description: "presentation_definition and presentation_definition_uri are mutually exclusive", InternalErro
this also applies to client_metadata?

2024-05-06 07:16 UTC, woutslakhorst reviewed
You could put the code blocks in separate private methods for readability.

2024-05-07 04:53 UTC, reinkrul approved these changes
this stuff is getting really hard to read

2024-05-07 09:07 UTC, merged