VCR: Remove @context default value from OAS
nuts-foundation/nuts-node pull request #3177
Opened 2024-06-08 06:31 UTC by reinkrul

It breaks code generation in Java. Can be safely deleted, we don't necerassily need it.

2024-06-10 07:03 UTC, woutslakhorst approved these changes

2024-06-10 09:43 UTC, gerardsn requested changes
add to description that it is the default to prevent magic behavior

2024-06-10 10:21 UTC, reinkrul commented
> add to description that it is the default to prevent magic behavior

It's already there:

> If omitted, the "https://nuts.nl/credentials/v1" context is used.

2024-06-11 07:50 UTC, gerardsn approved these changes

2024-06-11 13:07 UTC, merged