IAM: Provide authorization_server in access token requests
nuts-foundation/nuts-node pull request #3217
Opened 2024-07-01 18:12 UTC by reinkrul

To support other DID methods

2024-07-03 13:44 UTC, woutslakhorst requested changes

2024-07-03 13:44 UTC, woutslakhorst commented on auth/api/iam/api.go
> +func (r Wrapper) openid4vciMetadata(ctx context.Context, issuer *url.URL) (*oauth.OpenIDCredentialIssuerMetadata, *oauth.AuthorizationServerMetadata, error) {
Why the pointer to url? First thing is you call `.String()` on it.

2024-07-03 13:44 UTC, woutslakhorst commented on auth/api/iam/openid4vp.go
> +	if err != nil {
which error are you checking here?

2024-07-03 15:34 UTC, reinkrul commented on auth/api/iam/openid4vp.go
> +	if err != nil {
none, removed.

2024-07-05 05:50 UTC, woutslakhorst approved these changes

2024-07-05 06:57 UTC, merged