Final step of VDR refactor
nuts-foundation/nuts-node pull request #3245
Opened 2024-07-16 07:47 UTC by woutslakhorst

Part 3 of #3280

checking size....

2024-07-18 15:49 UTC, gerardsn requested changes
A bunch of small things. I'm braindead, so I hope the comments towards the end make sense.

🦆 means I was thinking out loud, not necessarily a request for change

2024-07-18 15:49 UTC, gerardsn commented on docs/_static/vdr/v2.yaml
>        - name: serviceId
🦆 implementers still need to inspect a DID document to find the `serviceId`. So not completely free of DID handling

2024-07-18 15:49 UTC, gerardsn commented on vdr/vdr.go
> +			id, _ := did.ParseDID(sqlDID.ID)
`MustParseDID` or handle error

2024-07-19 08:01 UTC, woutslakhorst commented on docs/_static/vdr/v2.yaml
> +  /internal/vdr/v2/did/{did}:
There'll be two APIs left under the DID tag: resolve and list. No need to create another tag. We'll have to assess the documentation and API structure when implementing the use of the subject.

2024-07-19 08:02 UTC, woutslakhorst commented on didman/didman_test.go
> +		vdr:                 mockVDR,
We should deprecate the entire didman module, so let's not spend to much time on it.

2024-07-19 08:06 UTC, woutslakhorst commented on docs/_static/vdr/v2.yaml
> +      summary: Creates new DID Documents for a subject.
Added doc

2024-07-19 08:07 UTC, woutslakhorst commented on docs/_static/vdr/v2.yaml
> +        description: Options for the DID creation. keys.assertionKey settings are ignored.
We should look at this when supporting RSA encryption keys

2024-07-19 08:08 UTC, woutslakhorst commented on docs/_static/vdr/v2.yaml
> +            $ref: '#/components/schemas/DIDDocument'
just generic API design, you always return the resource you create.

2024-07-19 08:17 UTC, woutslakhorst commented on vdr/api/v2/api.go
> +	if request.Body.Subject != nil {
StrictHandler in generated code always set it

2024-07-19 08:17 UTC, woutslakhorst commented on docs/_static/vdr/v2.yaml
>      CreateDIDOptions:
We're creating DIDs for a Subject

2024-07-19 08:22 UTC, woutslakhorst commented on vdr/didnuts/manager.go
> +var ErrInvalidOptions = errors.New("create request has invalid combination of options: SelfControl = true and CapabilityInvocation = false")
removed as well

2024-07-19 08:24 UTC, woutslakhorst commented on vdr/didnuts/manager.go
better to clean up later since it would introduce more lines to review

2024-07-19 08:28 UTC, woutslakhorst commented on vdr/vdr.go
> +	sqlDIDResolver      resolver.DIDResolver
the `sqlDIDResolver` is for owned docs. will rename

2024-07-19 08:30 UTC, woutslakhorst commented on vdr/vdr.go
> +	nutsDocumentManager didsubject.DocumentManager
I added godoc: it's deprecated and for the v1 api

2024-07-19 08:36 UTC, woutslakhorst commented on vdr/didsubject/management.go
to abstract when used anywhere else.

2024-07-19 08:43 UTC, woutslakhorst commented on vdr/management/management.go
moved to resolver. It's used in 1 place (to resolve NutsComm addresses) so we might delete it in the future.

2024-07-19 08:47 UTC, woutslakhorst commented on vdr/vdr.go
> +		}
renamed it

2024-07-19 09:03 UTC, woutslakhorst commented on vdr/vdr.go
> +		alsoKnownAs := make([]didsubject.DID, 0)
coming from a map this would require initialising an index and incrementing it. For this operation I rather have less code than performance.

2024-07-19 09:03 UTC, woutslakhorst commented on vdr/vdr.go
> +	docs := make([]did.Document, 0)
coming from a map this would require initialising an index and incrementing it. For this operation I rather have less code than performance.

2024-07-19 09:33 UTC, woutslakhorst commented on docs/_static/vdr/v2.yaml
>          * 500 - An error occurred while processing the request
since it's ID (or fragment) is the same as the previous one. No changes are made but the service is still returned as successfully added.

2024-07-19 09:34 UTC, woutslakhorst commented on vdr/vdr.go
> +		service.ID = GenerateIDForService(id, service)
Added test for duplicate

2024-07-19 10:19 UTC, woutslakhorst commented
@gerardsn will be checking coverage next

2024-07-19 11:04 UTC, woutslakhorst commented on vdr/vdr.go
> +	r.didResolver.(*resolver.DIDResolverRouter).Register(didkey.MethodName, didkey.NewResolver())
had to keep the cast since some APIs already call `Resolver()` at `New`

2024-07-23 10:14 UTC, gerardsn approved these changes

2024-07-23 11:52 UTC, merged