remove sub from access token introspection
nuts-foundation/nuts-node pull request #3354
Opened 2024-09-10 10:13 UTC by woutslakhorst

closes #3351

2024-09-10 11:16 UTC, gerardsn requested changes
failing test

2024-09-10 11:16 UTC, gerardsn commented on docs/_static/auth/v2.yaml
>            description: RFC7662 - Service-specific string identifier or list of string identifiers representing the intended audience for this token, as defined in JWT [RFC7519].
`aud` should also be removed?

2024-09-12 19:22 UTC, woutslakhorst commented on docs/_static/auth/v2.yaml
>            description: RFC7662 - Service-specific string identifier or list of string identifiers representing the intended audience for this token, as defined in JWT [RFC7519].
is not used in s2s flow afaik

2024-09-13 04:47 UTC, reinkrul approved these changes

2024-09-13 06:49 UTC, gerardsn approved these changes

2024-09-13 07:02 UTC, merged