Auto set CreatedAt for new DID documents
nuts-foundation/nuts-node pull request #3365
Opened 2024-09-13 09:33 UTC by gerardsn

closes #3364

2024-09-13 10:23 UTC, woutslakhorst requested changes

2024-09-13 10:23 UTC, woutslakhorst commented on vdr/didsubject/did_document_test.go
> +		time.Sleep(time.Second) // make sure doc.CreatedAt < doc.UpdatedAt
try to prevent this. Could be done by setting a timeNow func in the package.

2024-09-13 10:24 UTC, woutslakhorst commented on vdr/didsubject/did_document_test.go
> +		time.Sleep(time.Second) // make sure doc.CreatedAt < doc.UpdatedAt
but using gorm autoCreate makes this totally impossible...

2024-09-13 10:25 UTC, woutslakhorst commented on vdr/didsubject/did_document_test.go
> +		time.Sleep(time.Second) // make sure doc.CreatedAt < doc.UpdatedAt
you could manually adjust the field value in the DB (low level) and then call update

2024-09-13 10:55 UTC, gerardsn commented
Now also start counting document versions at 0 instead of 1

2024-09-16 06:53 UTC, woutslakhorst approved these changes

2024-09-16 07:18 UTC, merged