add validator for x509 credential attributes
nuts-foundation/nuts-node pull request #3617
Opened 2024-12-18 09:32 UTC by woutslakhorst

closes #3599

2024-12-18 13:20 UTC, gerardsn requested changes
doesn't complete CRL checks mentioned in referenced issue

2024-12-18 13:20 UTC, gerardsn commented on vcr/credential/validator.go
> +			unscaped, _ := url.PathUnescape(policySplit[i+1])
panics if `[i+1]` is out of bounds

2024-12-18 13:20 UTC, gerardsn commented on vcr/credential/validator.go
> +	}
add `else` with helpful error message

2024-12-18 13:20 UTC, gerardsn commented on vcr/credential/validator.go
> +	var target = make([]map[string]interface{}, 0)
micro optimize for expected length
```suggestion
	var target = make([]map[string]interface{}, 1)
```

2024-12-18 13:20 UTC, gerardsn commented on vcr/credential/validator.go
> +func validatePolicyAssertions(credential vc.VerifiableCredential) error {
missing test coverage on several error cases

2024-12-19 06:02 UTC, reinkrul reviewed
Looks fine aside from Gerard's comments

2024-12-19 06:02 UTC, reinkrul commented on vcr/credential/validator.go
> +		for i := 1; i < len(policySplit); i += 2 {
could check for `modulo 2 == 1`. If not, it's invalid?

2024-12-20 11:56 UTC, gerardsn approved these changes
tests fail on #3625

2024-12-20 13:47 UTC, merged