Move engine datadir to core config
nuts-foundation/nuts-node pull request #46
Opened 2021-02-04 07:30 UTC by reinkrul

In practice you'll probably want to have all data files in the same place, if not you can symlink them.

2021-02-04 13:34 UTC, woutslakhorst requested changes
- failing tests
- rebase on master?
- some documentation on which files to expect in the datadir?

2021-02-05 05:41 UTC, reinkrul commented
> * failing tests
> * rebase on master?
> * some documentation on which files to expect in the datadir?

I documented it as part of backup recommedations in "running in production".

2021-02-05 08:01 UTC, woutslakhorst requested changes

2021-02-05 09:46 UTC, woutslakhorst approved these changes

2021-02-05 10:00 UTC, merged