Refactor engine into interfaces
nuts-foundation/nuts-node pull request #51
Opened 2021-02-08 16:47 UTC by woutslakhorst

Closes #29

2021-02-08 21:41 UTC, woutslakhorst commented
Increase in code is largely due to the extra interfaces, which results in more funcs and mocks

2021-02-08 21:44 UTC, woutslakhorst commented
and lots of files changed due to running gofmt/goimport

2021-02-09 08:26 UTC, reinkrul requested changes
Although I understand why things are the way the are, what I don't like;

- The 'types' package per engine since packages should describe its functional purpose (we don't make a `util` or `consts` package) rather than what technicalities it contains
- Now the `Crypto`, `VDR` and `Network` structs are very much tied to `pflags` and `cobra` since the structs now contains functions which return them. It feels like we're mixing layers here (core functionality v.s. auxillary functionality to load the engine's configuration).

Any ideas?

2021-02-09 10:28 UTC, reinkrul approved these changes

2021-02-09 10:31 UTC, merged