Core: allow authentication to be configured on API endpoints
nuts-foundation/nuts-node pull request #615
Opened 2021-11-16 15:19 UTC by reinkrul

Fixes https://github.com/nuts-foundation/nuts-node/issues/540

2022-08-23 08:56 UTC, reinkrul commented on http/engine.go
> +	}
```suggestion
	case TLSMode(""):
		fallthrough
	case TLSDisabledMode:
		startFn = echoServer.Start
	default:
		return nil, fmt.Errorf("invalid TLS mode: %s", cfg.TLSMode)
	}
```

2022-08-23 08:56 UTC, reinkrul commented on http/ratelimiter.go
> +type InternalRateLimiterStore struct {
unexport

2022-08-24 15:13 UTC, gerardsn requested changes
Nice work.
It is a large PR, so many comments/questions.

Still needed
- [ ] Some documentation on the lifecycle or expected usage of the tokens. (Ignore this point if this is just a gap in my knowledge.)
- [ ] A lot of code and therefore tests have moved around and some test appear to be deleted. Coverage seems to be missing some things as well, but not sure if this is due to this PR. A double check on this would be great.

2022-08-25 04:23 UTC, reinkrul commented on core/http_client.go
> +func TestResponseCode(expectedStatusCode int, response *http.Response) error {
out of scope, but will do

2022-08-25 07:58 UTC, reinkrul commented on docs/_static/auth/v1.yaml
> +  securitySchemes:
Unfortunately not

2022-08-25 08:16 UTC, reinkrul commented on core/client_config.go
>  }
Exactly.

2022-08-25 08:17 UTC, reinkrul commented on docs/pages/deployment/cli-reference.rst
> +nuts http gen-token
https://github.com/nuts-foundation/nuts-node/issues/1377

2022-08-25 08:24 UTC, reinkrul commented on echo/echo_integration_test.go
>  import (
to core

2022-08-25 08:25 UTC, reinkrul commented on main.go
> +	err := cmd.Execute(ctx, cmd.CreateSystem(cancel))
Probably nothing

2022-08-25 08:29 UTC, reinkrul commented on core/client_config.go
> +const clientConfigFileName = ".nuts-client.cfg"
Will document it in new "API Authentication" page

2022-08-25 08:35 UTC, reinkrul commented on core/client_config.go
> +	}
Will document it to make it less magic

2022-08-25 08:35 UTC, reinkrul commented on core/client_config.go
> +var userHomeDirFn = os.UserHomeDir
Discussed

2022-08-25 08:37 UTC, reinkrul commented on http/engine.go
> +	}
will add test

2022-08-26 09:10 UTC, gerardsn requested changes
Couple of things left

2022-08-26 09:10 UTC, gerardsn commented on core/client_config.go
> +const clientConfigFileName = ".nuts-client.cfg"
still needs to be added to documentation

2022-08-26 09:10 UTC, gerardsn commented on http/engine.go
> +func (h Engine) applyBindMiddleware(echoServer EchoServer, path string, excludePaths []string, serverConfig core.ServerConfig, cfg InterfaceConfig) error {
```yaml
http:
  default:
    address: :1323
  alt:
    internal: # auth config is NOT accepted when address is not specified. /internal does not require a token with this config
      auth:
        type: token
    n2n: # does require token when address is specified
      address: :1323
      auth:
        type: token
```
The config above does not require a token when `http.alt.internal.auth` is set but `http.alt.internal.address` is not. If this is expected behavior it should be clearly documented.

2022-08-26 13:16 UTC, merged