Auth: fix clockskew test by making the skew larger (slow CirlceCI)
nuts-foundation/nuts-node pull request #676
Opened 2021-12-13 16:25 UTC by reinkrul

2021-12-13 18:03 UTC, dmeijboom requested changes
`s.clockSkew` is already multiplied by `time.Millisecond`

2021-12-13 19:18 UTC, stevenvegt approved these changes

2021-12-14 07:33 UTC, woutslakhorst commented
> `s.clockSkew` is already multiplied by `time.Millisecond`

Then a test just outside the clock skew should be added to validate

2021-12-15 07:29 UTC, reinkrul commented
> `s.clockSkew` is already multiplied by `time.Millisecond`

It was, but in the wrong location. The clockSkew was being passed around as 5000 milliseconds as `time.Duration`, which then actually is 5000 nanoseconds. Before being used it was converted to milliseconds, (`* time.Milliseconds`), but that should've done at the moment the clockSkew is converted from `int` to `time.Duration`. Otherwise, one could falsely assume that the `5000` as `clockSkew int` == `5000 milliseconds clockSkew time.Duration` (while it was in nanoseconds).

Therefore I renamed `clockSkew int` to `clockSkewInMilliseconds int` to avoid confusing about the units, and then immediately convert it to actual milliseconds the moment we derive a `time.Duration` from it.

2021-12-15 07:50 UTC, dmeijboom approved these changes
LGTM

2021-12-15 07:50 UTC, dmeijboom commented on auth/services/oauth/oauth_test.go
> +		ctx.oauthService.clockSkew = 1 * time.Millisecond // because 0 multiplied by 0 equals 0, rather use 1 millisecond (small clock skew), better test.
Nitpick: `1 * time.Millisecond` is the same as `time.Millisecond`

2021-12-15 08:36 UTC, merged