Network: fix node DID not being passed to v2
nuts-foundation/nuts-node pull request #725
Opened 2022-01-10 18:39 UTC by reinkrul

Taken from https://github.com/nuts-foundation/nuts-node/pull/708/commits/b1fc658016b22bd13cc8b5b94dea465e82c79c33

The `nodeDIDResolver` passed to `v2.New()` (create v2 protocol instance) got passed the default, emtpy node DID resolver. After that, it's overwritten with a resolver that contains the actual node DID. But since it's overwritten, v2 doesn't get the new, populated node DID resolver. Leading to node DID not being populated when encountering a private TX. Simply moving the initialization be before the protocol init fixes this.

Not really unit testable, since it calls package functions (`v2.New`), which can't be mocked. It's also a private member of v2 protocol, so not accessible for assertion. Integration-testable by https://github.com/nuts-foundation/nuts-node/pull/708

2022-01-10 19:51 UTC, woutslakhorst requested changes

2022-01-10 19:51 UTC, woutslakhorst commented on network/network.go
> +		n.nodeDIDResolver = &transport.FixedNodeDIDResolver{}
leave this one in the initializer?

2022-01-11 10:16 UTC, reinkrul commented
Not blocking at this moment, also fixed in one of the succeeding PRs.

2022-01-11 10:26 UTC, woutslakhorst approved these changes

2022-01-11 10:34 UTC, merged