Feature/vcr/add ldproof
nuts-foundation/nuts-node pull request #810
Opened 2022-02-09 16:24 UTC by stevenvegt

2022-02-18 16:03 UTC, woutslakhorst requested changes
- missing copyrights

2022-02-18 16:03 UTC, woutslakhorst commented on vcr/signature/ldutils.go
> +		nextLoader = ld.NewDefaultDocumentLoader(nil)
untested

2022-02-22 09:10 UTC, stevenvegt commented on vcr/assets/assets/contexts/lds-jws2020-v1.ldjson
> +{
Afaik you cannot add comments to json and the json-ld spec does not have a comment field or equivalent.

2022-02-22 09:13 UTC, stevenvegt commented on vcr/assets/assets/contexts/nuts.ldjson
> +{
I can make it empty and add actual data in further PRs.

2022-02-24 09:16 UTC, stevenvegt commented on vcr/signature/proof/proof.go
> +
Not sure: the SignedDocument is currently not really a thing in the VC standards
Perhaps if we want to extend the go-did library with cryptographic operation support.

2022-02-24 09:22 UTC, stevenvegt commented on vcr/verifier/verifier.go
> +// TODO: check for revoked credentials.
The v1 api currently has this logic implemented in the vcr.go. These are needed for the v2 api to be complete and are part of other PRs.

2022-02-24 11:53 UTC, woutslakhorst approved these changes

2022-02-24 12:08 UTC, merged