VCR: Allow searching on VC ID in v2 API
nuts-foundation/nuts-node pull request #906
Opened 2022-03-22 13:01 UTC by reinkrul

2022-03-23 10:53 UTC, woutslakhorst requested changes
as stated by https://nuts-foundation.gitbook.io/drafts/rfc/rfc011-verifiable-credential#3.4-identifiers

IDs are unique, so adding the `resolve` would be a better fit. Searching will automatically be supported when moving to semantic search

2022-03-23 13:18 UTC, reinkrul commented
> as stated by https://nuts-foundation.gitbook.io/drafts/rfc/rfc011-verifiable-credential#3.4-identifiers
> 
> IDs are unique, so adding the `resolve` would be a better fit. Searching will automatically be supported when moving to semantic search

Why must they be unique? There's no way to guarantee other issuers don't issue the same ID?

I'd say the combination issuer + ID must be unique (actually just like in X.509)

2022-03-24 05:09 UTC, reinkrul commented
> > > as stated by https://nuts-foundation.gitbook.io/drafts/rfc/rfc011-verifiable-credential#3.4-identifiers
> > > IDs are unique, so adding the `resolve` would be a better fit. Searching will automatically be supported when moving to semantic search
> > 
> > 
> > Why must they be unique? There's no way to guarantee other issuers don't issue the same ID?
> > I'd say the combination issuer + ID must be unique (actually just like in X.509)
> 
> IDs are currently required to be DID+ # + some ID, that makes them unique

(just checked, the check on ID format is missing in the current code base)

When we support other VCs types, this requirement might not apply. So why not just make them non-unique? There's no APIs that will break.

2022-03-24 07:43 UTC, woutslakhorst commented
They must be unique for the oauth flow since they are referenced by ID in the access token. Also revocation depends on the IDs.

2022-03-24 13:09 UTC, reinkrul commented
I created a separate PR to add `Resolve(id)` to the v2 API: https://github.com/nuts-foundation/nuts-node/pull/913

2022-03-24 13:27 UTC, reinkrul commented
> If a resolve is added, is this still needed? It'll be removed for v2

It would still be nice to be able to search on ID? (even though it will probably be supported when we support actual JSON-LD  searching)

2022-03-25 09:54 UTC, reinkrul commented
Probably irrelevant, and will be succeeded by actual JSON-LD-backed storage.

2022-03-25 09:54 UTC, closed without merging