Add link to documentation in readme
nuts-foundation/nuts-node pull request #944
Opened 2022-04-04 10:37 UTC by reinkrul

2022-04-04 14:07 UTC, woutslakhorst requested changes
README is al borked

2022-04-04 14:07 UTC, woutslakhorst commented on README.rst
> +    docker-compose pull
its `docker compose pull/up` these days. Minus the hyphen

2022-04-04 14:07 UTC, woutslakhorst commented on README_template.rst
> +.. include:: docs/pages/getting-started/0-hello-world-docker.rst
You made a booboo

2022-04-07 12:12 UTC, reinkrul commented
> README is al borked

?

2022-04-07 13:15 UTC, woutslakhorst requested changes

2022-04-07 13:15 UTC, woutslakhorst commented on docs/pages/getting-started/0-hello-world-docker.rst
> +.. _running-docker:
duplicate tag:

```
/Users/wout.slakhorst/nedap_healthcare/nuts-node/docs/pages/getting-started/0-hello-world-docker.rst:4: WARNING: duplicate label running-docker, other instance in /Users/wout.slakhorst/nedap_healthcare/nuts-node/docs/pages/getting-started/1-running-docker.rst
/Users/wout.slakhorst/nedap_healthcare/nuts-node/docs/pages/getting-started/1-running-docker.rst:4: WARNING: duplicate label running-docker, other instance in /Users/wout.slakhorst/nedap_healthcare/nuts-node/docs/pages/getting-started/0-hello-world-docker.rst
```

found using:
`cd docs & make html`

2022-04-11 07:10 UTC, woutslakhorst approved these changes

2022-04-11 07:57 UTC, merged