Iss88 fix duplicate slice flags
nuts-foundation/nuts-node pull request #99
Opened 2021-02-26 12:31 UTC by woutslakhorst

fixes #88

2021-02-26 12:57 UTC, woutslakhorst commented
@gerardsn

2021-03-01 09:55 UTC, reinkrul commented
Weird unrelated changes in `go.sum`?

2021-03-01 09:56 UTC, reinkrul requested changes
Changes look good an sich, but documentation generation is now broken (works on master);

```
make update-docs
go run ./docs
panic: read .: is a directory

goroutine 1 [running]:
main.generateServerOptions(0xc00041f780)
	/Users/rein.krul/workspace/nuts-node/docs/config-options-docs.go:30 +0x3de
main.main()
	/Users/rein.krul/workspace/nuts-node/docs/config-options-docs.go:16 +0x45
exit status 2
make: *** [gen-docs] Error 1
```

Edit: I see this is actually applicable to the other PR this one is based on.

2021-03-01 12:13 UTC, reinkrul approved these changes

2021-03-01 14:33 UTC, merged